title: Yilin Wen's Homepage
page-top-title: Yilin Wen
top-section-bg-text: Yilin Wen's Homepage
home-subtitle: Yilin Wen&ensp;|&ensp;文艺林
copyright-text: '&copy; Yilin Wen 2023-2025. All Rights Reserved.'
