title: Yilin Wen's Homepage
page-top-title: Yilin Wen
top-section-bg-text: Yilin Wen's Homepage
home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
